# Setup
title:        Dalisha Rivera-Rodriguez
tagline:      
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Dalisha Rivera-Rodriguez
  url:        http://DalishaRivera.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
theme: jekyll-theme-cayman
